name: Deploy and TestSprite E2E Tests 
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
  integration-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Generate App Token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.COMPANY_APP_ID }}
          private-key: ${{ secrets.COMPANY_APP_PRIVATE_KEY }}

      - name: TestSprite Action
        id: testsprite
        uses: TestSprite/github-action@main
        with:
          testsprite_api_key: 'sk-user-uM5Z1zV5bkrj5ET0GUVysYqDEUzzZwRfGkF1hmu6-cjph6-DB8UUo59h87SY1wITcpMXAHoCN1guA_-LDQxxuyZJhl2z96Poi79gaTo3N0rxKz1HL-poBJZrxHa0v75tc8k'
          github-token: ${{ steps.get_token.outputs.token }}
          base_url: ${{ github.event_name == 'pull_request' && format('https://ecommerce-platform-ecommerce-platform-pr-{0}.up.railway.app/', github.event.pull_request.number) || 'https://ecommerce-platform-production-f7c4.up.railway.app' }}
